record-announcement:
  enable-chat-message: true
  enable-log-message: true

compatibility:
  generic-vanish: true

advanced:
  debugging:
    enabled: false
    categories: [ "*" ]

metadata:
  installed-version: 2
  original-version: 2
  generated-with: "${project.version}"
