# PeakPlayersRecord by lokka30
messages:

  announcement:
    enabled: true
    text:
      - ' '
      - '&b&nPeak Players Record&r'
      - '&7A new record of peak players online has been set, with &b%players%&7 players online!'
      - ' '

  help:
    - ' '
    - '&b&nPeak Players Record&7 by lokka30&r'
    - ' '
    - '&f&nAvailable commands:&r'
    - '&8 &m->&b /ppr&8 - &7view command info'
    - '&8 &m->&b /ppr reload&8 - &7reload config'
    - ' '

  reload:
    start:
      - '&b&lPeakPlayersRecord: &7Reloading config...'

    finish:
      - '&b&lPeakPlayersRecord: &7Reload complete.'

  no-permission:
    - '&b&lPeakPlayersRecord: &7You don''t have access to that.'

  usage:
    - '&b&lPeakPlayersRecord: &7Usage: &b/ppr [reload]'

data:
  currentPeak: 0
  playerListAtPeak: "N/A"

debug: false