name: OnlineRecord
version: '${project.version}'
authors: [ lokka30 ]
main: io.github.arcaneplugins.onlinerecord.OnlineRecord
description: '${project.description}'
api-version: '1.13'

# Commands
commands:
  onlinerecord:
    description: 'Manage the OnlineRecord plugin.'
    aliases: [ or ]
    usage: /<command> [reload]

# Permissions
permissions:
  onlinerecord.*:
    default: op
    description: 'Contains all permissions from the resource.'
    children:
      onlinerecord.command: true
      onlinerecord.command.reload: true

  onlinerecord.command:
    default: true
    description: 'Ability to run the ''/or'' (base) command.'

  onlinerecord.command.reload:
    default: op
    description: 'Ability to run the ''/or reload'' command. User also requires the permission ''onlinerecord.command''.'