# Plugin Information
name: OnlineRecord
version: ${project.version}
author: lokka30

# Code Information
main: me.lokka30.onlinerecord.OnlineRecord
api-version: '1.13'

# Commands
commands:
  onlinerecord:
    description: 'Manage the resource.'
    aliases: [ or ]
    usage: /<command> [reload]

# Permissions
permissions:
  onlinerecord.*:
    default: op
    description: 'Contains all permissions from the resource.'
    children:
      onlinerecord.command: true
      onlinerecord.command.reload: true

  onlinerecord.command:
    default: op
    description: 'Ability to run the ''/or'' command.'

  onlinerecord.command.reload:
    default: op
    description: 'Ability to run the ''/or reload'' command. User also requires the permission ''onlinerecord.command''.'